class css_selector(object):
    NAV_LOGIN_BTN = ".shopee-page-wrapper.shopee-page-wrapper--home .navbar-wrapper.container-wrapper ul > li:nth-child(5)"
    NAV_USER_INFO = ".shopee-page-wrapper.shopee-page-wrapper--home .navbar-wrapper.container-wrapper .navbar__link.navbar__link--tappable.navbar__link--hoverable.navbar__link--account .navbar__link-text.navbar__link-text--normal-case"
    LOGIN_POP_ACCOUNT = "#modal input[name='loginKey']"
    LOGIN_POP_PASSWORD = "#modal input[name='password']"
    LOGIN_POP_SUBMIT_BTN = "#modal > aside > div > div > div > div:nth-child(1) > div:nth-child(2) button:nth-child(2)"
    SEARCH_BAR = ".shopee-searchbar .shopee-searchbar-input__input"
    SEARCH_RESULT_LIST = ".container > div[role='main']"
    CATEGORY_MAN_CLOTHING = ".shopee-page-wrapper .section-category-list .image-carousel__item-list-wrapper > ul > li:nth-child(1) > div > a:nth-child(2)"
    INIT_PAGE_POP_CLOSE_BTN = ".shopee-popup__container > .shopee-popup__close-btn"